// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UniversityExample.Data;

namespace UniversityExample.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20180213214657_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UniversityExample.Models.ClassModel", b =>
                {
                    b.Property<string>("ClassID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Credits");

                    b.Property<string>("Department");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ClassID");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("UniversityExample.Models.Enrollment", b =>
                {
                    b.Property<int>("StudentID");

                    b.Property<string>("ClassID");

                    b.Property<int>("EnrollmentID");

                    b.HasKey("StudentID", "ClassID");

                    b.HasAlternateKey("EnrollmentID");

                    b.HasIndex("ClassID");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("UniversityExample.Models.StudentsModel", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("StudentID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("UniversityExample.Models.Enrollment", b =>
                {
                    b.HasOne("UniversityExample.Models.ClassModel", "Class")
                        .WithMany("Enrollment")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniversityExample.Models.StudentsModel", "Student")
                        .WithMany("Enrollment")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
